apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
    - name: debian-container
      image: debian
      volumeMounts:
        - name: shared-volume
          mountPath: /html
      command:
        ["bash", "-c", "while true; do date >> /html/index.html; sleep 1; done"]
