apiVersion: v1
kind: Pod
metadata:
  name: app-secret
spec:
  containers:
    - name: redis
      image: redis:latest
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/foo"
  volumes:
    - name: secret-volume
      secret:
        secretName: simple-secret
