apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: app
    image: us-west2-docker.pkg.dev/annular-mesh-431721-j0/devops/gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8080
  imagePullSecrets:
  - name: gcr-secret
